### ISSUE TITLE
Friends.map is not a function

### ISSUE THREAD

**Issue by Asim-Avhad** [ed-roh/MERNSocialMedia#80]
Solved the issue thanks

**Comment by gowthamoff** [comment]
use null check
   {friends?.map?.((friend) => (
          <Friend
            key={friend._id}
            friendId={friend._id}
            name={`${friend.firstName} ${friend.lastName}`}
            subtitle={friend.occupation}
            userPicturePath={friend.picturePath}
          />
        )) ?? []}
